tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "nodenv/nodenv"
brew "awscli"
brew "direnv"
brew "fish"
brew "ghq"
brew "git"
brew "harfbuzz"
brew "librsvg"
brew "mas"
brew "mysql"
brew "nodenv"
brew "qt"
brew "poppler"
brew "rbenv"
brew "vim"
brew "vips"
brew "nodenv/nodenv/nodenv-default-packages"
cask "1password"
cask "android-studio"
cask "appcleaner"
cask "cyberduck"
cask "discord"
cask "docker"
cask "fantastical"
cask "figma"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "google-japanese-ime"
cask "hyper"
cask "imageoptim"
cask "insomnia"
cask "istat-menus"
cask "karabiner-elements"
cask "logitech-options"
cask "mimestream"
cask "netnewswire"
cask "ngrok"
cask "postico"
cask "raycast"
cask "sequel-ace"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "zoom"
mas "Bear", id: 1091189122
mas "DaftCloud", id: 1320450034
mas "One Thing", id: 1604176982
mas "Tweetbot", id: 1384080005
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
