#!/bin/zsh

#MISE dir="{{cwd}}"
#MISE description="Fix node version"
#MISE alias="fnv"

node_version=$(mise latest node@"${1:-latest}")

if [[ ! "$node_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "$1 is not a valid Node.js version tag."

  return 1
fi

echo "$node_version" | tee .node-version
