alias c "code"
alias fp "fixpack"
alias g "git"
alias github-release "conventional-github-releaser -p angular"
alias n "npm"
alias v "vim"
alias y "yarn"
alias yw "yarn workspace"
alias yws "yarn workspaces"
