alias c "code"
alias cr "cd (ghq root)/(ghq list | fzf)"
alias fp "fixpack"
alias g "git"
alias github-release "conventional-github-releaser -p angular"
alias n "npm"
alias pn "pnpm"
alias v "vim"
alias y "yarn"
alias yw "yarn workspace"
alias yws "yarn workspaces"
