syntax enable

set number
set ruler
set title

set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent
set smartindent

set hlsearch
set incsearch
set ignorecase
set smartcase
set wrapscan

set backspace=2

" Use system clipboard
set clipboard=unnamed
