#!/bin/bash

set -e

log_info () {
  echo "ℹ️ $1"
}

log_warn () {
  echo "⚠️ $1"
}

log_success () {
  echo "✅ $1"
}

# このリポジトリの場所はマシン固有の状態で、チェックアウト内の Git の管理対象外のファイル（home/.config/mise/conf.d/dotfiles-root.toml）に mise の dotfiles.root 設定として記録する
# インストール後は ~/.config/mise がチェックアウトへのシンボリックリンクになるので、mise はこのファイルをグローバルの設定の一部として読み込む
# $DOTFILES_DIR は、明示した環境変数 > 記録済みの設定 > 旧来の dotfiles-dir ファイル > デフォルト の順に決める

XDG_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"

if [ -z "$DOTFILES_DIR" ] && type mise &>/dev/null && [ -f "$XDG_CONFIG_DIR/mise/conf.d/dotfiles-root.toml" ]; then
  # `mise settings get` は参照できるすべての設定ファイルをマージするので、プロジェクトの設定がグローバルの値を隠さないように $HOME から実行する
  # dotfiles.root は常に <checkout>/home の形式で書き込む（組み込みのデフォルト値はこの形式に一致しない）ので、*/home の値だけを記録済みとみなす
  PERSISTED_ROOT="$( (cd "$HOME" && mise settings get dotfiles.root) 2>/dev/null || true)"
  case "$PERSISTED_ROOT" in
    */home) DOTFILES_DIR="${PERSISTED_ROOT%/home}" ;;
  esac
fi

# mise を使う前の構成（~/.config/dotfiles/dotfiles-dir にパスを保持し、シェルの起動のたびに .zshenv が読み込んでいた）からの移行
# すべてのマシンで install.sh を再実行したら、このブロックと後述のクリーンアップを削除する
LEGACY_DOTFILES_DIR_FILE="$XDG_CONFIG_DIR/dotfiles/dotfiles-dir"

if [ -z "$DOTFILES_DIR" ] && [ -f "$LEGACY_DOTFILES_DIR_FILE" ]; then
  read -r DOTFILES_DIR < "$LEGACY_DOTFILES_DIR_FILE"
fi

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/src/github.com/p-chan/dotfiles}"

if ! pgrep oahd >&/dev/null; then
  log_info "Installing Rosetta 2..."

  sudo softwareupdate --install-rosetta --agree-to-license

  log_success "Successfully installed Rosetta 2."
else
  log_info "Rosetta 2 already installed."
fi

if ! xcode-select -p &>/dev/null; then
  log_info "Installing Command Line Tools..."

  xcode-select --install

  until xcode-select -p &>/dev/null; do
    sleep 10
  done

  log_success "Successfully installed Command Line Tools."
else
  log_info "Command Line Tools already installed."
fi

if [ ! -d "$DOTFILES_DIR" ]; then
  log_info "Cloning dotfiles..."

  git clone https://github.com/p-chan/dotfiles.git "$DOTFILES_DIR"

  log_success "Successfully cloned dotfiles."
else
  log_info "dotfiles already cloned."
fi;

# チェックアウトが存在するので、$DOTFILES_DIR をシンボリックリンクを含まない絶対パスに正規化する
# どの方法（明示した環境変数、記録済みの設定、旧来のファイル、デフォルト）で決めた場合も、ここを通る
# 相対パスは呼び出し元のカレントディレクトリによって意味が変わるため
# 以降の手順ではディレクトリを移動するし、記録する dotfiles.root はどのディレクトリからでも有効である必要がある
# `pwd -P` はシンボリックリンクを解決するので、記録するパスがチェックアウトへのたどり方に依存しない
# ディレクトリが存在しなければ、set -e によってここで中断する
# CDPATH を引き継ぐと `cd` が解決したディレクトリを出力し、コマンド置換の結果に混ざるので、空にしている
DOTFILES_DIR="$(CDPATH= cd -- "$DOTFILES_DIR" && pwd -P)"

if [ -d "$DOTFILES_DIR" ]; then
  log_info "Change remote URL of dotfiles to SSH from HTTPS..."

  cd "$DOTFILES_DIR"

  git remote set-url origin git@github.com:p-chan/dotfiles.git

  cd "$HOME"

  log_success "Successfully changed remote URL of dotfiles."
else
  log_warn "$DOTFILES_DIR not found. Skipping dotfiles remote URL changing."
fi

# マシン固有のチェックアウトの場所を、mise の dotfiles.root として記録する
# ~/.config/mise はディレクトリごと home/.config/mise にシンボリックリンクされるので、このファイルはチェックアウト内（Git の管理対象外）に置く
# 専用のファイルにすることで、install.sh が config.toml や他の conf.d のファイルに触れないようにしている
MISE_DOTFILES_ROOT_FRAGMENT="$DOTFILES_DIR/home/.config/mise/conf.d/dotfiles-root.toml"

# TOML の基本文字列では、バックスラッシュとダブルクォートをエスケープする必要がある
TOML_ESCAPED_DIR="${DOTFILES_DIR//\\/\\\\}"
TOML_ESCAPED_DIR="${TOML_ESCAPED_DIR//\"/\\\"}"

DESIRED_FRAGMENT="$(printf '%s\n' \
  '# Generated by scripts/install.sh — machine-local, gitignored.' \
  '# Records where this dotfiles checkout lives. To move the checkout,' \
  '# re-run scripts/install.sh with DOTFILES_DIR set to the new location.' \
  '[settings]' \
  "dotfiles.root = \"$TOML_ESCAPED_DIR/home\"")"

if [ ! -f "$MISE_DOTFILES_ROOT_FRAGMENT" ] || [ "$(cat "$MISE_DOTFILES_ROOT_FRAGMENT")" != "$DESIRED_FRAGMENT" ]; then
  log_info "Recording dotfiles location in mise config..."

  mkdir -p "$(dirname "$MISE_DOTFILES_ROOT_FRAGMENT")"
  printf '%s\n' "$DESIRED_FRAGMENT" > "$MISE_DOTFILES_ROOT_FRAGMENT"

  log_success "Successfully recorded dotfiles location ($DOTFILES_DIR)."
else
  log_info "dotfiles location already recorded ($DOTFILES_DIR)."
fi

log_info "Configuring dotfiles profiles..."

bash "$DOTFILES_DIR/scripts/configure-profiles.sh" "$DOTFILES_DIR"

log_success "Successfully configured dotfiles profiles."

# 移行のクリーンアップ: 旧来のファイルは、現在 dotfiles.root が記録している内容と重複する
# 前述の移行のブロックと一緒に削除する
if [ -f "$LEGACY_DOTFILES_DIR_FILE" ]; then
  rm "$LEGACY_DOTFILES_DIR_FILE"
  rmdir "$(dirname "$LEGACY_DOTFILES_DIR_FILE")" 2>/dev/null || true

  log_info "Removed legacy $LEGACY_DOTFILES_DIR_FILE (superseded by mise's dotfiles.root)."
fi

if ! type mise &>/dev/null; then
  log_info "Installing mise..."

  curl https://mise.run | sh

  log_success "Successfully installed mise."
else
  log_info "mise already installed."
fi

# mise.run はデフォルトで ~/.local/bin にインストールするので、新しいシェルを起動しなくても、このスクリプトの残りで使えるようにする
export PATH="$HOME/.local/bin:$PATH"

if ! type brew &>/dev/null; then
  log_info "Installing Homebrew..."

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  log_success "Successfully installed Homebrew."
else
  log_info "Homebrew already installed."
fi;

if [ -f /opt/homebrew/bin/brew ]; then
  log_info "Setting up Homebrew."

  eval "$(/opt/homebrew/bin/brew shellenv)"

  log_success "Successfully set up Homebrew."
else
  log_warn "/opt/homebrew/bin/brew not found. Skipping Homebrew setup."
fi

if type mise &>/dev/null; then
  log_info "Running mise bootstrap..."

  # mise bootstrap は github: のツールをいくつかインストールする
  # gh が使えてログイン済みでない限り、それぞれ認証なしの GitHub API（1 時間あたり 60 リクエスト）で解決される
  # 新しいマシンでは gh 自体もそうしたツールの 1 つなので、他のツールより先に、ここで gh をインストールして認証する
  log_info "Installing and authenticating gh..."

  mise install "github:cli/cli@latest"

  if ! mise exec "github:cli/cli@latest" -- gh auth status &>/dev/null; then
    # このログインは、mise の credential_command 用の API トークンを発行するためだけに行う
    # dotfiles のフェーズで実際の home/.config/gh/config.yml（git_protocol = ssh）がシンボリックリンクされる前に実行するので、ここでは https を強制する
    # SSH キーの検出とアップロードのプロンプトを省くため（省かないと、1Password の SSH エージェントがセットアップ済みであることに依存する）
    #
    # 実際の ~/.config/gh ではなく、一時的な GH_CONFIG_DIR でログインする
    # --git-protocol を付けると gh は config.yml を丸ごと書き込むが、そのパスは後述の dotfiles のフェーズで作成される、dotfiles が管理するシンボリックリンクであるため
    # 先に書き込むと、初回のインストールではシンボリックリンクと競合し、再実行ではリンク先のリポジトリのファイルを黙って上書きしてしまう
    # 実際の場所に置く必要があるのは hosts.yml（gh の認証情報への参照で、トークン自体はシステムのキーチェーンにある）だけで、dotfiles の管理対象ではないので、直接コピーしても安全
    GH_AUTH_TMP_CONFIG_DIR="$(mktemp -d)"

    GH_CONFIG_DIR="$GH_AUTH_TMP_CONFIG_DIR" \
    mise exec "github:cli/cli@latest" -- gh auth login --git-protocol https --skip-ssh-key

    mkdir -p "$XDG_CONFIG_DIR/gh"
    cp "$GH_AUTH_TMP_CONFIG_DIR/hosts.yml" "$XDG_CONFIG_DIR/gh/hosts.yml"
    rm -rf "$GH_AUTH_TMP_CONFIG_DIR"
  fi

  log_success "Successfully authenticated gh."

  # 以前のインストールで ~/.config/mise が別のチェックアウトにシンボリックリンクされていたら、ここで張り替える
  # 張り替えないと、mise は古い場所の設定を読み続ける（そしてその設定に収束させる）ため
  # 実体のディレクトリやファイルの場合は、dotfiles のフェーズで対話的に解決させる
  if [ -L "$XDG_CONFIG_DIR/mise" ] && [ "$(readlink "$XDG_CONFIG_DIR/mise")" != "$DOTFILES_DIR/home/.config/mise" ]; then
    ln -sfn "$DOTFILES_DIR/home/.config/mise" "$XDG_CONFIG_DIR/mise"

    log_info "Repointed $XDG_CONFIG_DIR/mise to this checkout."
  fi

  mise trust "$DOTFILES_DIR/home/.config/mise/config.toml"

  # macOS の GUI のプロビジョニング（Dock、Finder、ホスト名など）は使い捨ての CI ランナーでは意味がないので、以前の provisioning.sh と同様にスキップする
  # また、ランナーには独自の ~/.ssh があり dotfiles のエントリと競合するが、使い捨てのランナーなので強制的に上書きしても安全
  extra_args=""
  if [ "$CI" = "true" ]; then
    extra_args="--skip macos-defaults --force-dotfiles"
  fi

  # MISE_CONFIG_DIR を指定すると、mise はチェックアウト内の mise ディレクトリをグローバルの設定ディレクトリとして扱う
  # そのため、~/.config/mise のシンボリックリンクが存在する前でも、config.toml と conf.d/*.toml の両方が読み込まれる
  # dotfiles のフェーズでシンボリックリンクが作成されたあとは、デフォルトの場所も同じファイルを指す
  MISE_CONFIG_DIR="$DOTFILES_DIR/home/.config/mise" \
  mise bootstrap --yes $extra_args

  log_success "Successfully ran mise bootstrap."
else
  log_warn "mise command not found. Skipping mise bootstrap."
fi
