#!/bin/bash

set -e

log_info () {
  echo "ℹ️ $1"
}

log_warn () {
  echo "⚠️ $1"
}

log_success () {
  echo "✅ $1"
}

# Where this repo lives is machine-specific state, recorded as mise's
# dotfiles.root setting in a gitignored fragment inside the checkout
# (home/.config/mise/conf.d/dotfiles-root.toml). Once installed,
# ~/.config/mise symlinks into the checkout, so mise reads the fragment as
# part of its global config. Resolution order for $DOTFILES_DIR:
# explicit env > persisted setting > legacy dotfiles-dir file > default.

XDG_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"

if [ -z "$DOTFILES_DIR" ] && type mise &>/dev/null && [ -f "$XDG_CONFIG_DIR/mise/conf.d/dotfiles-root.toml" ]; then
  # `mise settings get` merges every config file it can see; run from $HOME
  # so a project config can't shadow the global value. dotfiles.root is
  # always written as <checkout>/home (and its builtin default doesn't match
  # that shape), so only */home values count as persisted.
  PERSISTED_ROOT="$( (cd "$HOME" && mise settings get dotfiles.root) 2>/dev/null || true)"
  case "$PERSISTED_ROOT" in
    */home) DOTFILES_DIR="${PERSISTED_ROOT%/home}" ;;
  esac
fi

# Migration from the pre-mise layout where ~/.config/dotfiles/dotfiles-dir
# held the path (it was read by .zshenv on every shell startup). Remove this
# block, and the cleanup below, once every machine has re-run install.sh.
LEGACY_DOTFILES_DIR_FILE="$XDG_CONFIG_DIR/dotfiles/dotfiles-dir"

if [ -z "$DOTFILES_DIR" ] && [ -f "$LEGACY_DOTFILES_DIR_FILE" ]; then
  read -r DOTFILES_DIR < "$LEGACY_DOTFILES_DIR_FILE"
fi

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/src/github.com/p-chan/dotfiles}"

if ! pgrep oahd >&/dev/null; then
  log_info "Installing Rosetta 2..."

  sudo softwareupdate --install-rosetta --agree-to-license

  log_success "Successfully installed Rosetta 2."
else
  log_info "Rosetta 2 already installed."
fi

if ! xcode-select -p &>/dev/null; then
  log_info "Installing Command Line Tools..."

  xcode-select --install

  until xcode-select -p &>/dev/null; do
    sleep 10
  done

  log_success "Successfully installed Command Line Tools."
else
  log_info "Command Line Tools already installed."
fi

if [ ! -d "$DOTFILES_DIR" ]; then
  log_info "Cloning dotfiles..."

  git clone https://github.com/p-chan/dotfiles.git "$DOTFILES_DIR"

  log_success "Successfully cloned dotfiles."
else
  log_info "dotfiles already cloned."
fi;

# Normalize $DOTFILES_DIR to an absolute, symlink-free path now that the
# checkout exists. Every resolution path (explicit env, persisted setting,
# legacy file, default) funnels through this: a relative path would change
# meaning with the caller's cwd — the steps below cd around, and the
# persisted dotfiles.root must stay valid from any directory. `pwd -P`
# resolves symlinks so the recorded path doesn't depend on how the checkout
# was reached; set -e aborts here if the directory is missing. An inherited
# CDPATH would make `cd` echo the resolved dir into the substitution, hence
# the blanking.
DOTFILES_DIR="$(CDPATH= cd -- "$DOTFILES_DIR" && pwd -P)"

if [ -d "$DOTFILES_DIR" ]; then
  log_info "Change remote URL of dotfiles to SSH from HTTPS..."

  cd "$DOTFILES_DIR"

  git remote set-url origin git@github.com:p-chan/dotfiles.git

  cd "$HOME"

  log_success "Successfully changed remote URL of dotfiles."
else
  log_warn "$DOTFILES_DIR not found. Skipping dotfiles remote URL changing."
fi

# Record the machine-local checkout location as mise's dotfiles.root. The
# fragment lives inside the checkout (gitignored) because ~/.config/mise is
# symlinked to home/.config/mise as a whole directory; a dedicated file keeps
# install.sh from ever touching config.toml or other conf.d fragments.
MISE_DOTFILES_ROOT_FRAGMENT="$DOTFILES_DIR/home/.config/mise/conf.d/dotfiles-root.toml"

# TOML basic strings need backslashes and double quotes escaped.
TOML_ESCAPED_DIR="${DOTFILES_DIR//\\/\\\\}"
TOML_ESCAPED_DIR="${TOML_ESCAPED_DIR//\"/\\\"}"

DESIRED_FRAGMENT="$(printf '%s\n' \
  '# Generated by scripts/install.sh — machine-local, gitignored.' \
  '# Records where this dotfiles checkout lives. To move the checkout,' \
  '# re-run scripts/install.sh with DOTFILES_DIR set to the new location.' \
  '[settings]' \
  "dotfiles.root = \"$TOML_ESCAPED_DIR/home\"")"

if [ ! -f "$MISE_DOTFILES_ROOT_FRAGMENT" ] || [ "$(cat "$MISE_DOTFILES_ROOT_FRAGMENT")" != "$DESIRED_FRAGMENT" ]; then
  log_info "Recording dotfiles location in mise config..."

  mkdir -p "$(dirname "$MISE_DOTFILES_ROOT_FRAGMENT")"
  printf '%s\n' "$DESIRED_FRAGMENT" > "$MISE_DOTFILES_ROOT_FRAGMENT"

  log_success "Successfully recorded dotfiles location ($DOTFILES_DIR)."
else
  log_info "dotfiles location already recorded ($DOTFILES_DIR)."
fi

# Migration cleanup: the legacy file duplicates what dotfiles.root records
# now. Remove together with the migration block above.
if [ -f "$LEGACY_DOTFILES_DIR_FILE" ]; then
  rm "$LEGACY_DOTFILES_DIR_FILE"
  rmdir "$(dirname "$LEGACY_DOTFILES_DIR_FILE")" 2>/dev/null || true

  log_info "Removed legacy $LEGACY_DOTFILES_DIR_FILE (superseded by mise's dotfiles.root)."
fi

if ! type mise &>/dev/null; then
  log_info "Installing mise..."

  curl https://mise.run | sh

  log_success "Successfully installed mise."
else
  log_info "mise already installed."
fi

# mise.run installs to ~/.local/bin by default; make it available for the
# rest of this script without requiring a new shell.
export PATH="$HOME/.local/bin:$PATH"

if ! type brew &>/dev/null; then
  log_info "Installing Homebrew..."

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  log_success "Successfully installed Homebrew."
else
  log_info "Homebrew already installed."
fi;

if [ -f /opt/homebrew/bin/brew ]; then
  log_info "Setting up Homebrew."

  eval "$(/opt/homebrew/bin/brew shellenv)"

  log_success "Successfully set up Homebrew."
else
  log_warn "/opt/homebrew/bin/brew not found. Skipping Homebrew setup."
fi

if type brew &>/dev/null; then
  log_info "Installing Homebrew packages..."

  brew bundle --file="$DOTFILES_DIR/Brewfile" --jobs=auto

  log_success "Successfully installed Homebrew packages."
else
  log_warn "brew command not found. Skipping Homebrew package installation."
fi

if type mise &>/dev/null; then
  log_info "Running mise bootstrap..."

  # mise bootstrap installs several github: tools, each resolved through the
  # unauthenticated GitHub API (60 requests/hour) unless gh is available and
  # logged in. On a fresh machine gh itself is one of those tools, so install
  # and authenticate it here first, ahead of the rest of the batch.
  log_info "Installing and authenticating gh..."

  mise install "github:cli/cli@latest"

  if ! mise exec "github:cli/cli@latest" -- gh auth status &>/dev/null; then
    # This login only needs to mint an API token for mise's credential_command;
    # it runs before the dotfiles phase symlinks the real
    # home/.config/gh/config.yml (git_protocol = ssh), so force https here to
    # skip the SSH key detection/upload prompt, which would otherwise depend
    # on 1Password's SSH agent already being set up.
    #
    # Log in through a scratch GH_CONFIG_DIR rather than the real
    # ~/.config/gh: --git-protocol makes gh write a full config.yml, but that
    # path is a dotfiles-managed symlink created later in the dotfiles phase
    # below. Writing there first would conflict with that symlink on a first
    # install, or silently overwrite the checked-in file through it on a
    # re-run. Only hosts.yml (gh's auth reference; the token itself lives in
    # the system keychain) needs to land in the real location, and it isn't
    # dotfiles-managed, so copying it there directly is safe.
    GH_AUTH_TMP_CONFIG_DIR="$(mktemp -d)"

    GH_CONFIG_DIR="$GH_AUTH_TMP_CONFIG_DIR" \
    mise exec "github:cli/cli@latest" -- gh auth login --git-protocol https --skip-ssh-key

    mkdir -p "$XDG_CONFIG_DIR/gh"
    cp "$GH_AUTH_TMP_CONFIG_DIR/hosts.yml" "$XDG_CONFIG_DIR/gh/hosts.yml"
    rm -rf "$GH_AUTH_TMP_CONFIG_DIR"
  fi

  log_success "Successfully authenticated gh."

  # If a previous install symlinked ~/.config/mise to another checkout,
  # repoint it now: mise would otherwise keep reading (and converging to)
  # the old location's config. A real directory or file is left for the
  # dotfiles phase to resolve interactively.
  if [ -L "$XDG_CONFIG_DIR/mise" ] && [ "$(readlink "$XDG_CONFIG_DIR/mise")" != "$DOTFILES_DIR/home/.config/mise" ]; then
    ln -sfn "$DOTFILES_DIR/home/.config/mise" "$XDG_CONFIG_DIR/mise"

    log_info "Repointed $XDG_CONFIG_DIR/mise to this checkout."
  fi

  mise trust "$DOTFILES_DIR/home/.config/mise/config.toml"

  # macOS GUI provisioning (Dock, Finder, hostname, etc.) doesn't make sense on
  # an ephemeral CI runner, so skip it there like the old provisioning.sh did.
  # The runner also ships its own ~/.ssh, which conflicts with the dotfiles
  # entry; forcing it is safe on a throwaway runner.
  extra_args=""
  if [ "$CI" = "true" ]; then
    extra_args="--skip macos-defaults --force-dotfiles"
  fi

  # MISE_CONFIG_DIR makes mise treat the checkout's mise directory as its
  # global config dir, so config.toml AND conf.d/*.toml load before the
  # ~/.config/mise symlink exists. Once the dotfiles phase creates that
  # symlink, the default location resolves to the same files.
  MISE_CONFIG_DIR="$DOTFILES_DIR/home/.config/mise" \
  mise bootstrap --yes $extra_args

  log_success "Successfully ran mise bootstrap."
else
  log_warn "mise command not found. Skipping mise bootstrap."
fi
