# Homebrew requires non-official taps to be explicitly trusted (tap trust);
# trust only the cask we actually use instead of the whole tap.
tap "steipete/tap", trusted: { cask: "codexbar" }
# eza can't be mise-managed: it ships no macOS binaries on GitHub Releases
# (so github: fails), and mise's brew backend can't link its ca-certificates
# dependency on machines where Homebrew already provides that file.
brew "eza"
cask "1password-cli"
cask "1password"
cask "arc"
cask "claude"
cask "cleanshot"
cask "codex-app"
cask "codexbar"
cask "cyberduck"
cask "docker-desktop"
cask "fantastical"
cask "figma"
cask "firefox"
cask "font-source-han-code-jp"
cask "font-symbols-only-nerd-font"
cask "gcloud-cli"
cask "ghostty"
cask "google-chrome"
cask "google-japanese-ime"
cask "handy"
cask "istat-menus"
cask "karabiner-elements"
cask "logi-options+"
cask "microsoft-edge"
cask "mimestream"
cask "multipass"
cask "rapidapi"
cask "raycast"
cask "slack"
cask "utm"
cask "visual-studio-code"
