name: Check PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
      - name: Check PR Title
        run: |
          node .github/scripts/check-pr-title.ts "${{ github.event.pull_request.title }}"
